{
  "openapi": "3.0.0",
  "info": {
    "title": "Microserviço de Clientes | easyOrder 4.0 Documentação da API.",
    "description": "easyOrder - Tech Challenge (4) da Pos Tech SOAT - Microserviço de Clientes",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000/"
    }
  ],
  "paths": {
    "/cliente/cadastrar": {
      "post": {
        "tags": [
          "Clientes"
        ],
        "summary": "Cadastrar Cliente",
        "description": "Realiza o Cadastro de um novo Cliente com dados fornecidos no corpo da requisição.<br>  - Retorna o Id de Cliente como chave para continuidade no Pedido.<br>  - Não é permitido o cadastro de mais de um cliente com o mesmo CPF.<br><br>  [ Endpoint para integração ao sistema de autoatendimento ]",
        "responses": {
          "200": {
            "description": "Cliente cadastrado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "resultado_cadastro": {
                      "type": "boolean",
                      "example": true
                    },
                    "mensagem": {
                      "type": "string",
                      "example": "Cliente cadastrado com sucesso"
                    },
                    "cliente": {
                      "example": {
                        "id": "c8076edc-b7ce-4cc6-803f-f3466ef434aa",
                        "cpf": "123.456.789-10",
                        "nome": "Nome do Cliente",
                        "email": "exemplo.email@dominio.com"
                      }
                    }
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "properties": {
                    "resultado_cadastro": {
                      "type": "boolean",
                      "example": true
                    },
                    "mensagem": {
                      "type": "string",
                      "example": "Cliente cadastrado com sucesso"
                    },
                    "cliente": {
                      "example": {
                        "id": "c8076edc-b7ce-4cc6-803f-f3466ef434aa",
                        "cpf": "123.456.789-10",
                        "nome": "Nome do Cliente",
                        "email": "exemplo.email@dominio.com"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Ocorreu um erro inesperado",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "mensagem": {
                      "type": "string",
                      "example": "Erro: Não foi possível cadastrar o cliente"
                    }
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "properties": {
                    "mensagem": {
                      "type": "string",
                      "example": "Erro: Não foi possível cadastrar o cliente"
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Cliente"
              },
              "example": {
                "cpf": "12345678910",
                "nome": "Nome do Cliente",
                "email": "exemplo.email@dominio.com"
              }
            }
          }
        }
      }
    },
    "/cliente/atualizar": {
      "put": {
        "tags": [
          "Clientes"
        ],
        "summary": "Atualizar Cliente",
        "description": "Atualiza o Cadastro de um Cliente existente, através dos dados fornecidos no corpo da requisição.<br>  - Utiliza CPF como chave de identificação, retorna o detalhe do cadastro e Id do Cliente.<br><br>  [ Endpoint para integração aos sistemas administrativo e/ou de loja/autoatendimento ]",
        "responses": {
          "200": {
            "description": "Cliente atualizado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "resultado_atualizacao": {
                      "type": "boolean",
                      "example": true
                    },
                    "mensagem": {
                      "type": "string",
                      "example": "Cliente atualizado com sucesso"
                    },
                    "cliente": {
                      "example": {
                        "id": "c8076edc-b7ce-4cc6-803f-f3466ef434aa",
                        "cpf": "123.456.789-10",
                        "nome": "Nome Atualizado",
                        "email": "exemplo.atualizado@dominio.com"
                      }
                    }
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "properties": {
                    "resultado_atualizacao": {
                      "type": "boolean",
                      "example": true
                    },
                    "mensagem": {
                      "type": "string",
                      "example": "Cliente atualizado com sucesso"
                    },
                    "cliente": {
                      "example": {
                        "id": "c8076edc-b7ce-4cc6-803f-f3466ef434aa",
                        "cpf": "123.456.789-10",
                        "nome": "Nome Atualizado",
                        "email": "exemplo.atualizado@dominio.com"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Ocorreu um erro inesperado",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "mensagem": {
                      "type": "string",
                      "example": "Erro: Não foi possível atualizar o cliente"
                    }
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "properties": {
                    "mensagem": {
                      "type": "string",
                      "example": "Erro: Não foi possível atualizar o cliente"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Cliente"
              },
              "example": {
                "cpf": "12345678910",
                "nome": "Nome Atualizado",
                "email": "exemplo.atualizado@dominio.com"
              }
            }
          }
        }
      }
    },
    "/cliente/listar": {
      "get": {
        "tags": [
          "Clientes"
        ],
        "summary": "Listar Clientes",
        "description": "Lista todos os clientes cadastrados.<br><br>  [ Endpoint para integração ao sistema administrativo ]",
        "responses": {
          "200": {
            "description": "Clientes listados com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "mensagem": {
                      "type": "string",
                      "example": "Clientes listados com sucesso"
                    },
                    "clientes": {
                      "type": "array",
                      "items": {
                        "properties": {
                          "id": {
                            "type": "string",
                            "example": "1"
                          },
                          "cpf": {
                            "type": "string",
                            "example": "000.000.000-00"
                          },
                          "nome": {
                            "type": "string",
                            "example": "Fulano de Tal"
                          },
                          "email": {
                            "type": "string",
                            "example": "teste@teste.com"
                          }
                        }
                      }
                    }
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "properties": {
                    "mensagem": {
                      "type": "string",
                      "example": "Clientes listados com sucesso"
                    },
                    "clientes": {
                      "type": "array",
                      "items": {
                        "properties": {
                          "id": {
                            "type": "string",
                            "example": "1"
                          },
                          "cpf": {
                            "type": "string",
                            "example": "000.000.000-00"
                          },
                          "nome": {
                            "type": "string",
                            "example": "Fulano de Tal"
                          },
                          "email": {
                            "type": "string",
                            "example": "teste@teste.com"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Ocorreu um erro inesperado",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "mensagem": {
                      "type": "string",
                      "example": "Erro: Clientes não encontrados."
                    }
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "properties": {
                    "mensagem": {
                      "type": "string",
                      "example": "Erro: Clientes não encontrados."
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/cliente/auth/{cpf}": {
      "get": {
        "tags": [
          "Clientes"
        ],
        "summary": "[Novo] Autenticar Cliente",
        "description": "Autenticar Cliente via CPF.<br>  - Retorna o Id do cliente, caso encontrado, como chave para continuidade no Pedido.<br><br>  [ Endpoint para integração ao sistema de autoatendimento ]",
        "parameters": [
          {
            "name": "cpf",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "CPF do Cliente sem pontuação",
            "example": "12345678910"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Solicitação Inválida"
          }
        }
      }
    },
    "/health": {
      "get": {
        "tags": [
          "Outros"
        ],
        "summary": "Health check",
        "description": "",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    },
    "schemas": {
      "ID": {
        "type": "string",
        "minLength": 36,
        "maxLength": 36,
        "format": "uuid",
        "example": "29a81eeb-d16d-4d6c-a86c-e13597667307"
      },
      "Cliente": {
        "type": "object",
        "properties": {
          "cpf": {
            "type": "string",
            "minLength": 11,
            "maxLength": 11,
            "example": "12345678910"
          },
          "nome": {
            "type": "string",
            "minLength": 0,
            "maxLength": 255,
            "example": "Nome do cliente"
          },
          "email": {
            "type": "string",
            "minLength": 0,
            "maxLength": 255,
            "example": "exemplo.email@dominio.com"
          }
        }
      }
    }
  }
}